name: Build Tutorial Image

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, rolling]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_IMAGE: ghcr.io/ros-planning/moveit2_tutorials:${{ matrix.ROS_DISTRO }}
      # PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'ros-planning/moveit2_tutorials') }}
      PUSH: ${{ (github.event_name != 'pull_request') }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Tutorial Image
        uses: docker/build-push-action@v3
        with:
          file: .docker/Dockerfile
          build-args: |
                ROS_DISTRO=${{ matrix.ROS_DISTRO }}
                BASE_BRANCH=${{ env.BASE_IMAGE_BRANCH }}
          target: tutorial_image
          push: ${{ env.PUSH }}
          no-cache: false
          tags: |
            ${{ env.GH_IMAGE }}-tutorial
